version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.1.1
  continuation: circleci/continuation@0.1.2

workflows:
  on-commit:
    jobs:
      - dynamic/continue:
          modules: |
            helm
            scripts
